# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-08 22:20
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.db import migrations, models

import eox_tagging.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name=b'Public identifier')),
                ('tag_value', models.CharField(max_length=150)),
                ('tag_type', models.CharField(max_length=150)),
                ('access', models.PositiveIntegerField(choices=[(1, b'PUBLIC'), (2, b'PROTECTED'), (3, b'PRIVATE')], default=eox_tagging.constants.AccessLevel(1))),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveIntegerField(choices=[(0, b'INVALID'), (1, b'VALID')], default=eox_tagging.constants.Status(1), editable=False)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('tagged_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('belongs_to_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('resource_locator', models.CharField(blank=True, max_length=150, null=True)),
                ('belongs_to_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to_tag_type', to='contenttypes.ContentType')),
                ('tagged_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_type', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('resource_locator', 'tagged_object_id')]),
        ),
    ]
