# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-28 21:10
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name=b'Public identifier')),
                ('tag_value', models.CharField(max_length=150)),
                ('tag_type', models.CharField(max_length=150)),
                ('access', models.PositiveIntegerField(choices=[(1, b'Public'), (2, b'Protected'), (3, b'Private')], default=1)),
                ('status', models.PositiveIntegerField(choices=[(1, b'Valid'), (0, b'Invalid')], default=1, editable=False)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
    ]
