# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-01 19:37
from __future__ import unicode_literals

from django.db import migrations, models

import eox_tagging.constants


class Migration(migrations.Migration):

    dependencies = [
        ('eox_tagging', '0002_auto_20200529_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='uid',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='tag',
            name='access',
            field=models.PositiveIntegerField(choices=[(1, b'PUBLIC'), (2, b'PROTECTED'), (3, b'PRIVATE')], default=eox_tagging.constants.AccessLevel(1)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, b'INVALID'), (1, b'VALID')], default=eox_tagging.constants.Status(1), editable=False),
        ),
    ]
